forum1:
  url: https://whatboyswant.com/forums/
  base_url: https://whatboyswant.com
  username: colionel
  password: belgarath
  category1: Nude Public Babes
  category2: Non-Nude Public Babes

forum2:
  url: http://themousepad.yuku.com/
  username: colionel
  password: belgarath
  category1: Candid Content
  category2: Foot Model Content

forum3:
  url: https://theperfectboobs.net/index.php
  username: vdaubrytest@gmail.com
  password: belgarath
  category1: Amateurs
  category2: Models / Glamour